[package]
name = "eruption"
version = "0.0.3"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]
edition = "2018"
description = "Linux user-mode driver for the ROCCAT Vulcan 100/12x series keyboards"
repository = "https://gitlab.com/X3n0m0rph59/eruption-roccat-vulcan.git"
homepage = "https://x3n0m0rph59.gitlab.io/eruption-roccat-vulcan/"
license = "GPLv3+"
readme = "README.md"

[features]
default = []

[dependencies]
log = "0.4.6"
pretty_env_logger = "0.3.0"
ctrlc = { version = "3.1.2", features=["termination"] }
clap = "2.33.0"
confy = "0.3.1"
hidapi = { git = "https://github.com/X3n0m0rph59/hidapi-rs.git", branch = "master" }
udev = "0.2.0"
evdev-rs = "0.2.0"
hexdump = "0.1.0"
itertools = "0.8.0"
lazy_static = "1.3.0"
rand = "0.6.5"
rlua = "0.16.3"
sysinfo = "0.8.4"
systemstat = "0.1.4"
procinfo = "0.4.2"

[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 8
panic = 'unwind'

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'unwind'
